[package]
name = "noughtsandcrosses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-ord = "0.3.2"
rand = "0.8.5"
rayon = "1.6.1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = 'abort'
incremental = true
